const path = require("path");
const session = require("express-session");
const flash = require("express-flash");
const MongoDBStore = require("connect-mongo");
const expressLayout = require("express-ejs-layouts");
const passport = require("passport");
const passportInit = require("../lib/passport");

const setMiddlewares = (app, express) => {
  //session setup and configurations
  app.use(
    session({
      secret: "thisismysecret",
      save: false,
      store: MongoDBStore.create({
        mongoUrl: "mongodb://localhost:27017/pizza-order",
        ttl: 1000 * 60 * 60 * 24, // time to live
        autoRemove: "native", //auto remove expired sessions
      }),
      saveUninitialized: false,
      cookie: {
        maxAge: 1000 * 60 * 60 * 24,
        secure: false,
      },
    })
  );
  app.use(flash());

  // passport configurations
  passportInit();
  app.use(passport.initialize());
  app.use(passport.session());

  // Global middlewares
  app.use(express.urlencoded({ extended: false }));
  app.use(express.json());

  app.use((req, res, next) => {
    res.locals.session = req.session;
    res.locals.user = req.user; // generated by passport.serialize and derserialize;
    console.log(req.user);
    next();
  });

  //templates
  app.use(express.static(path.join("public")));
  app.use(expressLayout);
  app.set("views", path.join(__dirname, "../../../resources/views"));
  app.set("view engine", "ejs");
};

module.exports = setMiddlewares;
